pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/manju65char/nodejs_application.git'
            }
        }

    }
}

